services:
  # Database Service (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: dzenn-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Opsional: Buka jika ingin akses dari luar (Gunakan firewall!)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Service (Dzenn App)
  app:
    image: ghcr.io/brokarim/dzenn-live:latest
    container_name: dzenn-app
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge
